server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: sa
    password: sqlServer123
    url: jdbc:sqlserver://localhost:1433;databaseName=nhacmoi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: off

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000